### ISSUE TITLE
Make it possible to access cloud from anywhere

### ISSUE THREAD

**Issue by miska** [owncloud/pi-image#5]
A big challenge is to provide a stable address users can configure their mobile and desktop clients to or send to friends who they want to give access to their ownCloud to. How do we solve this?
(edit this item with more info/progress)
# todo
- [x] configure the router to forward port 443 to the server using uPnP
- [x] create a IPv6 work-around solution using Teredo
- [ ] create a IPv6 work-around solution using tunnel to some broker
- [ ] document IPv6 work-around solutions in end-user understandable way
- [ ] provide instructions on router configuration in case auto-config doesn't work
- [ ] provide a proxy solution if the router configure doesn't work/is too hard
- [x] configure dyndns to have a stable address to reach the server

**Comment by miska** [comment]
People might want to access the cloud not only from home and they might not have public IPv4. So I created ownCloud application that will help them to get IPv6 and DynDNS. You can see the latest version here:
https://github.com/miska/ocipv6
https://apps.owncloud.com/content/show.php?content=174659

And more details are provided here:
http://michal.hrusecky.net/2015/12/getting-ipv6-for-your-owncloud/

Currently supports Teredo for routing so in theory should be easy to get at least some IPv6 and supports Dynv6 so there is a way to easily get permanent domain name.

**Comment by miska** [comment]
Added support for uPnP to my app, testing and visual appearance fixes (as other fixes) are welcome:
https://github.com/miska/ocipv6/commit/90b4e9eae2203c214394ba1c6b72201d5d89ed78

**Comment by enekux** [comment]
Awesome job @miska!
Before reading this post I also started to do my own research regarding UPnP and run into same client "miniupnpc" that you are using in your "OC IPv6" app. But of course you are far ahead doing the owncloud app... great!
From my tests I have noticed that if the router is rebooted the rules created by "miniupnpc" are lost... and I think that is not ideal. Instead, if the rules are manually added they stay.
I haven't found any special command in "miniupnpc" to make the rules permanent, the only way is or to add bash script to be run when interfaces are up or better to run cron job.
Here you have some examples:
https://pavelfatin.com/access-your-raspberry-pi-from-anywhere/

**Comment by oparoz** [comment]
@miska Is the todo list up to date?
